name: dmd
version: 2.088.0
summary: Reference compiler for the D programming language
description: |
    DMD ('Digital Mars D') is the reference compiler for the D
    programming language.  This package includes DMD together
    with the standard language runtime (druntime) and standard
    library (phobos).  Some of the core developer tools (rdmd,
    dustmite, and ddemangle) are also included.

confinement: classic
grade: stable

apps:
  dmd:
    command: bin/dmd
  ddemangle:
    command: bin/ddemangle
  dustmite:
    command: bin/dustmite
  rdmd:
    command: bin/rdmd

parts:
  dmd:
    source: https://github.com/dlang/dmd.git
    source-tag: &dmd-version v2.088.0
    source-type: git
    plugin: make
    makefile: posix.mak
    make-parameters:
    - AUTO_BOOTSTRAP=1
    - ENABLE_RELEASE=1
    organize:
      linux/bin32: bin
      linux/bin64: bin
    stage:
    - -bin/dmd.conf
    - -linux
    - -samples
    build-packages:
    - curl
    - g++

  dmd-config:
    plugin: dump
    source: dmd-config
    organize:
      dmd.conf: bin/dmd.conf

  dmd-license:
    plugin: dump
    source: doc
    organize:
      LICENSE: doc/LICENSE

  druntime:
    source: https://github.com/dlang/druntime.git
    source-tag: *dmd-version
    source-type: git
    plugin: make
    makefile: posix.mak
    make-parameters:
    - DMD_DIR=../../dmd/build
    - CFLAGS=$(MODEL_FLAG) -fPIC -DHAVE_UNISTD_H -O3 -Wa,-mrelax-relocations=no
    - PIC=1
    organize:
      src/druntime/import: import/druntime
    stage:
    - -src
    build-packages:
    - gcc
    after:
    - dmd

  phobos:
    source: https://github.com/dlang/phobos.git
    source-tag: *dmd-version
    source-type: git
    plugin: make
    makefile: posix.mak
    make-parameters:
    - DMD_DIR=../../dmd/build
    - DRUNTIME_PATH=../../druntime/build
    - VERSION=../../dmd/build/VERSION
    - CFLAGS=$(MODEL_FLAG) -fPIC -DHAVE_UNISTD_H -O3 -Wa,-mrelax-relocations=no
    - PIC=1
    organize:
      linux/lib32: lib32
      linux/lib64: lib64
      src/phobos: import/phobos
    stage:
    - -linux
    - -src
    build-packages:
    - gcc
    after:
    - dmd
    - druntime

  tools:
    source: https://github.com/dlang/tools.git
    source-tag: *dmd-version
    source-type: git
    plugin: make
    makefile: posix.mak
    make-parameters:
    - DMD_DIR=../../dmd/build
    - DRUNTIME_PATH=../../druntime/build
    - PHOBOS_PATH=../../phobos/build
    build-packages:
    - libcurl4-gnutls-dev
    stage:
    - bin/ddemangle
    - bin/dustmite
    - bin/rdmd
    after:
    - dmd
    - dmd-config
    - druntime
    - phobos
